# BUILD & PUSH WPPConnect-SERVER IMAGE TO GHCR
# -------------------------------------------
name: Build-and-Publish

on:
  push:
    branches: [ main ]          # bouwt op elke push naar main
  workflow_dispatch:            # handmatig starten kan ook

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read            # code clonen
      packages: write           # image naar GHCR pushen

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Log in op GitHub Container Registry met automatisch token
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Image tag (kies zelf; hier v1.37.1 + short SHA)
      - name: Set image tag
        id: vars
        run: echo "TAG=v1.37.1-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build \
            --tag ghcr.io/${{ github.repository_owner }}/wppconnect-server:${{ steps.vars.outputs.TAG }} \
            --tag ghcr.io/${{ github.repository_owner }}/wppconnect-server:latest \
            .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/wppconnect-server:${{ steps.vars.outputs.TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/wppconnect-server:latest
